### ISSUE TITLE
Fix cmake install

### ISSUE THREAD

**Issue by leofang** [conda-forge/thrust-feedstock#14]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

For context see https://github.com/conda-forge/cub-feedstock/issues/16 and https://github.com/conda-forge/cub-feedstock/issues/17.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by kkraus14** [comment]
Duplicate of #12
