### ISSUE TITLE
Sunsetting this feedstock?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/thrust-feedstock#19]
In PR ( https://github.com/conda-forge/staged-recipes/pull/21953 ), `cuda-cccl-impl` is being added, which contains and supersedes `thrust`.

Also this feedstock has been updated so that `thrust` conflicts with `cuda-cccl-impl` (or other CCCL packages) ( https://github.com/conda-forge/thrust-feedstock/pull/18 ). This conflict has also been applied as a repodata patch to old packages ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/428 ).

Since the current plan is not to update this any further, how do we want to go about sunsetting this feedstock?

* Do we want to alias this package?
* Should this package emit some kind of deprecation warning?
* Would it make sense to run a migration to move to the preferred package?
* Do we want to archive this feedstock?
* Anything else we should do?
* Also any thoughts on the order/timeline of these?

Edit: Related `cub` issue ( https://github.com/conda-forge/cub-feedstock/issues/24 )

**Comment by jakirkham** [comment]
cc @bdice @leofang @kkraus14

**Comment by kkraus14** [comment]
Given the plans related to `thrust`, `cub`, and `libcudacxx` that the team has publicly stated in wanting to move to a single package in the future, I would vote to archive this feedstock.

As far as a migration goes, we are quite far behind in packaging `thrust` / `cub` versions, they aren't in the global pinning, and there's a small number of recipes that use them. I don't think a migration would be particularly helpful / useful in this situation.

**Comment by bdice** [comment]
Agreed with @kkraus14. Let's archive thrust/cub and file follow-up issues for the [three packages depending on thrust/cub](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/428#issuecomment-1497978516). I would not do a migration, it's probably not needed.

**Comment by kkraus14** [comment]
@rongou @leofang you're the other two maintainers on this and the cub feedstocks. Does this plan work for you?

**Comment by leofang** [comment]
Despite I start making bad decisions tonight, I think this is a right move to sunset/archive this feedstock. I argued that we should set up a migrator, but it might require some manual work in each feedstock, so perhaps not much automation can help.

**Comment by rongou** [comment]
Sounds good to me.

**Comment by kkraus14** [comment]
Opened the PR to archive the thrust and cub feedstocks here: https://github.com/conda-forge/admin-requests/pull/702
